import Footer from '@/components/layouts/footer/footer';
import Header from '@/components/layouts/header/header';
import WalletContextProvider from '@/components/providers/wallet-context-provider';
import font from '@/lib/font';
import '@/styles/custom.scss';
import '@/styles/globals.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.clashDisplay.className}>
        <WalletContextProvider>
          <Header />
          <div
            id="background-cover"
            className="fixed left-0 top-0 h-full w-full"
          >
            {/* <DotPattern
            width={20}
            height={20}
            cx={1}
            cy={1}
            cr={1}
            className="fill-primary [mask-image:radial-gradient(500px_circle_at_center,white,transparent)]"
          /> */}
          </div>
          <main className="bg-background">{children}</main>
        </WalletContextProvider>
        <Footer />
      </body>
    </html>
  );
}
